"""Build autolabels_vq1_v2.json: the v1 labels with the three triage mechanisms handled.

  A (rate aliasing)   -> every instance gains 'body_rate' (rad/s at frame time, via
                         triagecheck_rates.py's matching path: frames.csv t_recv_wall_ns
                         -> imu.csv, |gyro| median over +/-50 ms) so training can
                         down-weight without re-scanning. No instance is changed for A --
                         the error is not fixable after the fact.
  B (behind a gate)   -> instances whose band+quad extent is covered >= thresh by a
                         NEARER gate's solid board (labelfix_occlusion.py) move to
                         labelfix_negatives_v2.json with visibility 'hidden', reason
                         'behind-gate' -- same schema convention as
                         autolabels_vq1_negatives.json.
  C (gate-1 pose)     -> gate-1 corners REGENERATED by projecting the refit full pose
                         (labelfix_gate1_pose.json: centre delta [-0.56 -0.05 +0.04] m,
                         rotation 1.7 deg; held-out corner error 2.59/27.6 ->
                         1.67/2.7 px median/p90) through the frame's pose. 'clipped' and
                         'size_px' are recomputed; the orange/occl_frac numbers are NOT
                         (they described the old quad -- 'gate1_refit': true marks this).
                         Gate-1 instances get their behind-gate fraction recomputed on
                         the NEW quad rather than taken from the flags file.

Everything else is byte-identical to v1. z is re-indexed contiguously per list (it is a
draw order); (key, gate) is the stable join key across v1/v2 -- a gate appears at most
once per frame.

    python3 pilot/perception/labelfix_build_v2.py

Reads autolabels_vq1.json, labelfix_gate1_pose.json, labelfix_occl_flags.json.
Writes autolabels_vq1_v2.json + labelfix_negatives_v2.json. Modifies neither v1 file.
"""

from __future__ import annotations

import json
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import label as L  # noqa: E402
from autolabel import canon  # noqa: E402
import labelfix_common as C  # noqa: E402
import labelfix_occlusion as O  # noqa: E402


def main():
    labels = json.load(open(os.path.join(HERE, 'autolabels_vq1.json')))
    g1 = json.load(open(os.path.join(HERE, 'labelfix_gate1_pose.json')))
    occl = json.load(open(os.path.join(HERE, 'labelfix_occl_flags.json')))
    thresh, flags = occl['thresh'], occl['flags']
    g1_pts = C.gate_corners(np.asarray(g1['centre']), np.asarray(g1['rvec']))
    gates = O.load_gate_set(os.path.join(HERE, 'labelfix_gate1_pose.json'))

    rates = C.RateLookup()
    tracks, ftimes = {}, {}
    out, neg = {}, {}
    n_regen, n_removed, n_inst = 0, 0, 0
    moves = []
    for key in sorted(labels):
        sess, fname = key.split('/', 1)
        sdir = os.path.join(C.SESSIONS, sess)
        if sess not in tracks:
            tracks[sess] = L.PoseTrack(sdir)
            ftimes[sess] = C.frame_times(sdir)
        pose = tracks[sess].at_time(ftimes[sess][fname])
        rate = rates.rate(key)
        keep, drop = [], []
        for i, d in enumerate(labels[key]):
            n_inst += 1
            d = dict(d)
            d['body_rate'] = None if rate is None else round(rate, 3)
            bf = flags.get(f'{key}#{i}', {'behind_frac': 0.0, 'behind': None})
            if d['gate'] == 1 and pose is not None:
                old = np.asarray(d['corners'], np.float64)
                uv, z = L.project(g1_pts, pose)
                if np.all(z > 0.1) and np.all(np.isfinite(uv)):
                    uv = canon(uv)
                    moves.append(float(np.linalg.norm(uv - canon(old), axis=1).mean()))
                    e = [float(np.linalg.norm(uv[(j + 1) % 4] - uv[j]))
                         for j in range(4)]
                    d['corners'] = [[round(float(u), 2), round(float(v), 2)]
                                    for u, v in uv]
                    d['size_px'] = round(max(e), 2)
                    d['clipped'] = bool(np.any(uv[:, 0] < 0) or
                                        np.any(uv[:, 0] > L.W - 1) or
                                        np.any(uv[:, 1] < 0) or
                                        np.any(uv[:, 1] > L.H - 1))
                    d['gate1_refit'] = True
                    n_regen += 1
                    # behind-gate on the NEW quad, not the stale flag
                    f2, gi2 = C.behind_gate_fraction(pose, gates, 1, uv)
                    bf = {'behind_frac': round(f2, 4), 'behind': gi2}
            if bf['behind_frac'] >= thresh:
                d['visibility'] = 'hidden'
                d['reason'] = 'behind-gate'
                d['behind_frac'] = bf['behind_frac']
                d['behind_gate'] = bf['behind']
                drop.append(d)
                n_removed += 1
            else:
                keep.append(d)
        if keep:
            for z, d in enumerate(keep):
                d['z'] = z
            out[key] = keep
        if drop:
            for z, d in enumerate(drop):
                d['z'] = z
            neg[key] = drop

    with open(os.path.join(HERE, 'autolabels_vq1_v2.json'), 'w') as fh:
        json.dump(out, fh, indent=1)
    with open(os.path.join(HERE, 'labelfix_negatives_v2.json'), 'w') as fh:
        json.dump(neg, fh, indent=1)
    m = np.asarray(moves)
    print(f'{n_inst} v1 instances -> {sum(len(v) for v in out.values())} kept, '
          f'{n_removed} removed behind-gate')
    print(f'gate-1 regenerated: {n_regen}; corner move median {np.median(m):.2f} px  '
          f'p90 {np.percentile(m, 90):.2f}  max {m.max():.1f}')
    print('wrote autolabels_vq1_v2.json + labelfix_negatives_v2.json')


if __name__ == '__main__':
    main()
